### ISSUE TITLE
Migrate `create_datasets.sh` from lingualibre.fr to lingualibre.org

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/operations#1]
### `/create_datasets.sh`
- [x] Migrate [create_datasets.sh](https://github.com/lingua-libre/operations/blob/master/create_datasets.sh) to `.org` : [done](https://github.com/lingua-libre/operations/commit/d4799b2f585a6b349ac6d00551673077fa945e03#diff-9447407a31f072a884fb839cabf04d6c8f553395f7a202a4985a380dc26080de)
- [x] Is there still any endpoint in https://lingualibre.org/bigdata/namespace/wdq/sparql ? seems to be a simple redirect, see screenshoot.
- [x] Deploy on server. @mickeybarber.

![Screenshot_2021-01-27_15-58-10](https://user-images.githubusercontent.com/1420189/106009374-89f95580-60b8-11eb-9bf1-fb2644c41b82.png)

**Comment by mickeybarber** [comment]
@hugolpz
There is a nginx redirection, lignualibre.fr to lingualibre.org since May 2020, but stats doesn't work  since only November. So I think it's not the same problem but I can still update create_datasets.sh

**Comment by hugolpz** [comment]
I see. Thanks for the dates. So we have 

### Key dates
- 2020, April 25 : before-last [/datasets/](https://lingualibre.org/datasets/) refresh. 
- 2020, May xx : migration to .org, 
- 2020, May 17 : last compilation of `lingualibre-all.zip`
- 2020, Nov. 05: last /datasets/* refresh for active language showing changes 

I suspects:
- 2020, April 25, 0x010C migrate folder and force-download all to start fresh ; `create_datasets.sh` is no more in line with enpoints
- 2020, May 17, 0x010C hand-runs specific command for creation of `lingualibre-all.zip`
- 2020, Nov. 05, 0x010C hand-runs specific command for creation of `*.zip` right before leaving France.

### Solution
Anyway, the current /datasets/ page is far behind the actual correct numbers visible on [Category:Lingua Libre pronunciation](https://commons.wikimedia.org/wiki/Category:Lingua_Libre_pronunciation).
Since this `create_datasets.sh` only affects the datasets folder and web page in an isolated manner.
Let's update `create_datasets.sh` on the server so this is done and we get more info. Maybe it will work. If it doesn't, I dig further : who runs this routine*, etc.

### Local test
[EDIT] I got my new monthly forfait so I was able to test `create_datasets.sh` locally. with both cases, **only changing the .fr vs .org**.

Finding: 
- `create_datasets.sh` with `.fr` -----> **FAILS**. Crashes INSTANTLY.
- `create_datasets.sh` with `.org` ---> **WORKS**. Seems to run properly for 30 seconds. Starts downloading. I stopped due to my 4G data limitations.

**So I think the migration may fix the datasets issue.**
Please replace `create_datasets.sh` on Wikimedia server by the latest version on github.

```bash
yug@yug-K401UB:~/Documents/CommonsDownloadTool$ # TEST WITH .fr #####################################
yug@yug-K401UB:~/Documents/CommonsDownloadTool$ sudo bash create_datasets.sh 
--> Force the download of recent changes...
(--------------------------------------------------------------------------------------Hugo: It crashes INSTANTLY with .FR !
Traceback (most recent call last):
  File "/home/yug/Documents/CommonsDownloadTool/commons_download_tool.py", line 220, in <module>
    get_params()
  File "/home/yug/Documents/CommonsDownloadTool/commons_download_tool.py", line 208, in get_params
    response = json.loads(response.text)['results']['bindings']
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--> Download and package ALL sounds...
Traceback (most recent call last):
  File "/home/yug/Documents/CommonsDownloadTool/commons_download_tool.py", line 220, in <module>
    get_params()
  File "/home/yug/Documents/CommonsDownloadTool/commons_download_tool.py", line 208, in get_params
    response = json.loads(response.text)['results']['bindings']
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
--> Package each language individually
--> Move all zip archives in the public datasets folder
mv: cannot stat '/tmp/datasets/*.zip': No such file or directory



yug@yug-K401UB:~/Documents/CommonsDownloadTool$ # TEST WITH .org #####################################
yug@yug-K401UB:~/Documents/CommonsDownloadTool$ sudo bash create_datasets.sh 
--> Force the download of recent changes...
(--------------------------------------------------------------------------------------Hugo: Here it keeps thinking for 5 secs)
--> Download and package ALL sounds...
(--------------------------------------------------------------------------------------Hugo: There it goes !! It seems to be downloading...)
(--------------------------------------------------------------------------------------Hugo: After 20s I quit CTRL+C to not ruin all my 4G forfait !)
^CTraceback (most recent call last):
  File "/home/yug/Documents/CommonsDownloadTool/commons_download_tool.py", line 220, in <module>
    get_params()
  File "/home/yug/Documents/CommonsDownloadTool/commons_download_tool.py", line 204, in get_params
    response = requests.post(sparql_url, data = {
  File "/usr/lib/python3/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 686, in send
    r.content
  File "/usr/lib/python3/dist-packages/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/lib/python3/dist-packages/requests/models.py", line 750, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 560, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 755, in read_chunked
    chunk = self._handle_chunk(amt)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 708, in _handle_chunk
    returned_chunk = self._fp._safe_read(self.chunk_left)
  File "/usr/lib/python3.8/http/client.py", line 612, in _safe_read
    data = self.fp.read(amt)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python
```





*: #2 : lingualibre.wikimedia.fr (BlazeGraph and LL bot server) has a cronjobs runing  `create_datasets.sh`.

### lingualibre.wikimedia.fr (BlazeGraph and LL bot server)
- CronJobs:
```
0 3 */2 * * /bin/bash /home/www/create_datasets.sh

**Comment by hugolpz** [comment]
@mickeybarber : 
- replaced the file
- ran it
I close this issue.
